name: Maintaining Higher Consciousness
favicon: null
layout_spectrum: 0.14189862669445574
typography_spectrum: 0.0396348861977458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1451227404177189
  lightness: 0.6258926382288337
  saturation: 0.8372447893489152
  rhythmicContrast: 0.9604708643164486
purpose: []
