name: Maintaining Higher Consciousness
favicon: null
layout_spectrum: 0.25387
typography_spectrum: 0.31657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#93795e'
    - '#ead8d1'
    - '#664030'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
